### ISSUE TITLE
[FEAT-REQ] Single node selection like radio button

### ISSUE THREAD

**Issue by sowka1995** [JairajJangle/react-native-tree-multi-select#68]
Hi, 

well done! Your control looks great, but is it possible to adapt your solution to single node selection? I need something exactly like this, but instead of checkboxes, for example, a radiobutton, where you can select only one node.

Thanks in advance for your answer!

**Comment by JairajJangle** [comment]
Hey there!

Thank you for your kind words! 😊

The functionality that you described can be implemented using the current version itself with a combination of these customizations and props: `onCheck` callback, `CheckboxComponent` / `CustomNodeRowComponent`, and the ref-exposed function: `unSelectNodes`.

Although there is no built-in support to implement single node selection directly, thanks to the high customizability of the `TreeView` component, the implementation is totally possible, specifically like this:
1. Use `CheckboxComponent` / `CustomNodeRowComponent` to create your own custom tree node component that uses a radio button instead of the checkbox.
2. Implement the `onCheck` callback to determine/store which tree node has been checked by the user.
3. Listen to `onCheck` and on each `onCheck` callback call the `unSelectNodes` ref function to unselect the previously checked node. This way you can ensure only one node is checked at a time.

I hope this helps! If you have any more questions or need further assistance, feel free to ask. 🙏

**Comment by sowka1995** [comment]
Thanks for the answer!.
Unfortunately, the program then falls into an infinite update loop after calling unselectNodes in the onCheck handler. Additionally, is it possible to disable auto selection of all direct children when we click on the parent? eg. when I click on the root then only this one node is selected not all childs

**Comment by JairajJangle** [comment]
Hey there! 👋

Thank you for your patience, and I appreciate your understanding! 🙏 I’ve updated the library to include a **selection propagation mechanism** to control auto-selection to parents and children. This feature is now available in [v1.5.0-beta.3](https://github.com/JairajJangle/react-native-tree-multi-select/releases/tag/v1.5.0-beta.3). While it’s not a direct solution to your issue, it provides the flexibility needed to address it.

To make things easier, I’ve created a **working demo on Expo Snack** to demonstrate exactly what you’re aiming for:  
[Expo Snack Link](https://snack.expo.dev/@futurejj/react-native-tree-multi-select-radio-button-example)

Additionally, here’s a **short video recording** of how it works:  
    <img src="https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExczJzbXNzZjA0cDE2ZjJrbWlkazQzemE0dXI3czJucWVjcXd1bHZuYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gEQbAu6WU0XzcngwCz/giphy.gif" alt="LiberPay_Donation_Button" height="550" > 
  </img>

I acknowledge there’s been a bit of a delay from my end—thanks for your patience with that. As this is an open-source project, it relies heavily on community support, so I hope you understand. 😊

Please give the beta version a try and let me know if it resolves your issue or if you encounter any other challenges. Looking forward to your feedback!

**Comment by sowka1995** [comment]
Hi, thank you for this solution! I returned to this project after a long time. I noticed that when we have a node selected, other nodes flash when expanding/collapsing. Do you know how to avoid this?

https://github.com/user-attachments/assets/a9405454-8734-4cc8-b086-564c1e81600f

**Comment by JairajJangle** [comment]
Hey there! 👋  

Thanks for reaching out, and welcome back to the project! 😊  

The flashing effect you're seeing when expanding/collapsing nodes is likely due to **list item recycling**, which is a common behavior in **FlashList**. Since items are reused for performance optimization, it can sometimes create a slight visual artifact where unchecked nodes momentarily appear checked.  

You can read more about FlashList’s recycling behavior here:  [FlashList Recycling Docs](https://shopify.github.io/flash-list/docs/recycling)

To avoid this issue, you could try:  
1. **Disabling animations** in **react-native-paper** if you're using their radio button component.  
2. Using a **custom checkbox component** that doesn’t have animations, ensuring a smoother visual transition.  

Let me know if this helps or if you need further clarification! 🚀

**Comment by sowka1995** [comment]
Hi, thanks for your answer!
I found a solution, when we add  _key={node.id}_ to <RadioButton /> component inside **_CustomNodeRowView** function then flashing dissapears :)

**Comment by JairajJangle** [comment]
Hey @sowka1995, glad to hear you found a solution! 😊  

However, I wanted to point out something from the FlashList documentation:  

> Using key prop inside your item and item's nested components will highly degrade performance.

You can read more about it here: https://shopify.github.io/flash-list/docs/fundamentals/performant-components#remove-key-prop

Instead, I’d recommend using the `keyExtractor` prop. It’s a much more efficient way to ensure proper identification of items while avoiding unnecessary re-renders. You can check out the details here: https://shopify.github.io/flash-list/docs/guides/layout-animation/

Let me know if you run into any issues while trying this! 🚀
