### ISSUE TITLE
[FEAT-REQ] Adding a callback to only receive the checked node 

### ISSUE THREAD

**Issue by Astremy** [JairajJangle/react-native-tree-multi-select#82]
Hello!
As stated in the other issue (https://github.com/JairajJangle/react-native-tree-multi-select/issues/81), I think it would be cool to have a way to receive only the selected node, if we want to handle things differently or to use the tree in another context than like options.

Currently, I'm using something like that:
```ts
function checkBox(current){
  let removed = save.filter((o) => current.indexOf(o) === -1);
  let added = current.filter((o) => save.indexOf(o) === -1);
  
  console.log(added);

  save = current;
}
```
which isn't too bad, but it's not very practical either. So I think it could be nice to get the checked/unchecked node directly in some way.

And maybe a way to get the full object (or a partial one) and not only the id, or a way to pass down more informations? Well, I feel like I will have to do another issue xD

**Comment by JairajJangle** [comment]
Hey there! 👋 Thanks for your patience and for sharing this!

I believe the functionality you're suggesting might introduce additional overhead on each checkbox state change, which I'd prefer to avoid in the core library for now.

I checked this again, and as of now, there isn’t a simpler or more direct way to achieve this other than comparing the last state with the current state – which is exactly how you're already handling it.

That said, I think your current method is on the right track! If you're open to it, using Lodash to calculate the difference might make things a bit cleaner. Here's an example of how you could implement it:

```javascript
import _ from 'lodash';

function checkBox(current) {
  const added = _.difference(current, save);
  const removed = _.difference(save, current);

  console.log(added);
  save = current;
}
```

This should make the comparison more concise while achieving the same result.

Since this can be implemented externally without too much hassle, I’ll go ahead and close this issue. If you feel there's anything else you'd like to explore, feel free to open another issue – I’m always happy to discuss! 😄

Thanks again for your input and for contributing to making the library better. 🙏
